### ISSUE TITLE
Run Project

### ISSUE THREAD

**Issue by mustafacoskuncom** [sislex/Angular2LoginDemo#1]
Hi, how we can run this project? You didnt write the following ways. I tried npm method but not run. Thanks for your help.

**Comment by sislex** [comment]
Hi, the project is not ready yet. I am playing with ang2 and will post a short instruction when I finish it (1 week approx.).

**Comment by mustafacoskuncom** [comment]
Ok man. Thanks and waiting for your Angular2 art :+1:
